# This is not intended to be a production-ready deployment; It is only intended to demonstrate
# how Catalyst may be deployed in a container environment.
# Carefully read and understand the entire configuration before using any part of it.
# By using this file, you are indicating your acceptance of the Minecraft EULA (https://www.minecraft.net/en-us/eula).
name: catalyst

services:
  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: catalyst_docker_compose
      POSTGRES_USER: catalyst_docker_compose
      POSTGRES_PASSWORD: catalyst_docker_compose
    volumes:
      - ./postgresql:/var/lib/postgresql/data

  pg-admin:
    image: dpage/pgadmin4:8.14
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: catalyst@example.com
      PGADMIN_DEFAULT_PASSWORD: catalyst

  # Sample mariadb container
  # Don't forget to update references in this file and the ../config/velocity-patch-set.json LP storage method
  # Comment out postgres images above (db and pg-admin)
  #  db:
  #    image: mariadb:11.2
  #    ports:
  #      - "3306:3306"
  #    environment:
  #      MYSQL_DATABASE: catalyst_docker_compose
  #      MYSQL_USER: catalyst_docker_compose
  #      MYSQL_PASSWORD: catalyst_docker_compose
  #      MARIADB_RANDOM_ROOT_PASSWORD: true
  #    volumes:
  #      - ./mariadb:/var/lib/mysql

  lp:
    image: ghcr.io/luckperms/luckperms:v5.4.151
    environment:
      # LUCKPERMS_STORAGE_METHOD: mariadb
      LUCKPERMS_STORAGE_METHOD: postgresql
      LUCKPERMS_DATA_ADDRESS: db
      # Use a different database and credentials in production
      LUCKPERMS_DATA_DATABASE: catalyst_docker_compose
      LUCKPERMS_DATA_USERNAME: catalyst_docker_compose
      LUCKPERMS_DATA_PASSWORD: catalyst_docker_compose

  proxy:
    image: itzg/mc-proxy:2024.6.0
    ports:
      - "25565:25565"
    environment:
      TYPE: VELOCITY
      VELOCITY_VERSION: 3.4.0-SNAPSHOT
      VELOCITY_BUILD_ID: 458
      PLUGINS: |
        https://download.luckperms.net/1568/velocity/LuckPerms-Velocity-5.4.151.jar
        https://cdn.modrinth.com/data/7IbzD4Zm/versions/Jp1p9BHR/SignedVelocity-Proxy-1.3.0.jar
        https://cdn.modrinth.com/data/1iWA0pjH/versions/rEHcRyPV/MCKotlinVelocity-1.4.0-k1.9.21.jar
      PATCH_DEFINITIONS: /server/velocity-patch-set.json
      # CATALYST_DB_TYPE: mariadb # default: postgresql
      # CATALYST_DB_URL: jdbc:mariadb://db/catalyst_docker_compose
      CATALYST_DB_URL: jdbc:postgresql://db/catalyst_docker_compose
      CATALYST_DB_USER: catalyst_docker_compose
      CATALYST_DB_PASSWORD: catalyst_docker_compose
      CATALYST_CHAT_DISCORD_ENABLED: false
      CATALYST_CHAT_DISCORD_BOT_TOKEN: "<token here>"
      CATALYST_CHAT_CHANNELS: |
        {
          "global": {
            "id": "global",
            "name": "<green>[Global]",
            "nameFormat": "<gold>[%backend.name%]</gold>%prefix% %displayname%",
            "contentFormat": "%content%",
            "messageFormat": "%channel.name% %name%: %content%",
            "commandAliases": [
               "g",
               "global"
            ],
            "alwaysVisible": true,
            "availableByDefault": true,
            "discordChannelId": "123456789"
          },
          "staff": {
            "id": "staff",
            "name": "<aqua>[Staff]",
            "nameFormat": "<gold>[%backend.name%]</gold>%prefix% %displayname%",
            "contentFormat": "%content%",
            "messageFormat": "<aqua>%channel.name% %name%: %content%",
            "commandAliases": [
               "sc",
               "staffchat"
            ],
            "alwaysVisible": true,
            "availableByDefault": false,
            "discordChannelId": "123456789"
          }
        }
    volumes:
      - ../../build/libs:/plugins
      - ../config/velocity.toml:/server/velocity.toml
      - ../config/forwarding.secret:/server/forwarding.secret
      - ../config/velocity-patch-set.json:/server/velocity-patch-set.json
      - ./proxy/plugins:/server/plugins

  paper-0:
    image: itzg/minecraft-server:2024.12.1
    expose:
      - 25565
    environment:
      TYPE: PAPER
      VERSION: "1.21.4"
      PAPER_CHANNEL: "experimental"
      PAPER_BUILD: "68"
      EULA: true # By using this environment variable, you are indicating your acceptance of the Minecraft EULA
      ONLINE_MODE: false
      PATCH_DEFINITIONS: /config/paper-patch-set.json
      PLUGINS: |
        https://cdn.modrinth.com/data/7IbzD4Zm/versions/TKC72r9l/SignedVelocity-Paper-1.3.0.jar
    volumes:
      - ./paper-0:/data
      - ../config/paper-patch-set.json:/config/paper-patch-set.json:ro

  paper-1:
    image: itzg/minecraft-server:2024.12.1
    expose:
      - 25565
    environment:
      TYPE: PAPER
      VERSION: "1.21.4"
      PAPER_CHANNEL: "experimental"
      PAPER_BUILD: "68"
      EULA: true # By using this environment variable, you are indicating your acceptance of the Minecraft EULA
      ONLINE_MODE: false
      PATCH_DEFINITIONS: /config/paper-patch-set.json
      PLUGINS: |
        https://cdn.modrinth.com/data/7IbzD4Zm/versions/TKC72r9l/SignedVelocity-Paper-1.3.0.jar
    volumes:
      - ./paper-1:/data
      - ../config/paper-patch-set.json:/config/paper-patch-set.json:ro
